### ISSUE TITLE
Undesired requests appear everytime launching the cachy-browser

### ISSUE THREAD

**Issue by HSidhiuwhfiunci** [CachyOS/CachyOS-Browser-Common#12]
Everytime I launch the cachy-browser and review the `about:networking`, there are always some undesired requests that connect to `firefox.settings.services.mozilla.com`, `content-signature-2.cdn.mozilla.net`
And I also review the `/usr/lib/cachy-browser/omni.ja`, which still got the 

```
  ENGINES_URLS: {
    "prod-main":
      "https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/search-config/records",
    "prod-preview":
      "https://firefox.settings.services.mozilla.com/v1/buckets/main-preview/collections/search-config/records",
    "stage-main":
      "https://firefox.settings.services.allizom.org/v1/buckets/main/collections/search-config/records",
    "stage-preview":
      "https://firefox.settings.services.allizom.org/v1/buckets/main-preview/collections/search-config/records",
  },
```
However they should be patched with `patches/sed-patches/stop-undesired-requests.patch`, but it seems doesn't work.

**Comment by vnepogodin** [comment]
Librewolf patches were removed
