### ISSUE TITLE
So I'm a librewolf user - tell me what, definitively, about Cachy Browser Differs from Librewolf

### ISSUE THREAD

**Issue by ilikenwf** [CachyOS/CachyOS-Browser-Common#4]
Patches, CFLAGS, LDFLAGS...

Prefs are a little less important since I already have custom settings and addons. Sorry if this is the wrong place to put this...but I assume the librewolf-bin builds are compiled for x86_64-v3...so...why use Cachy-Browser?

You explain that it has hardening but don't really elaborate or enumerate how/what differs.

**Comment by ptr1337** [comment]
> Patches, CFLAGS, LDFLAGS...
> 
> Prefs are a little less important since I already have custom settings and addons. Sorry if this is the wrong place to put this...but I assume the librewolf-bin builds are compiled for x86_64-v3...so...why use Cachy-Browser?
> 
> You explain that it has hardening but don't really elaborate or enumerate how/what differs.

librwolf-bin is NOT compiled with x86-64-v3.
Cachy-Browser uses a bunch of different patches. Cherry picked from librewolf as well as the gentoo patchset.

Cachy-Browsers config is based on librewolf, but pulls some tweaks from fastfox in.
Also it is compiled against our system libs and does enable more libs.
see:
https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/cachy-browser/PKGBUILD#L131-L161

If you are happy with librewolf - keep to use it. Its a great browser.
We just added our own quirks and changes, which are not going into librewolf upstream.

**Comment by ilikenwf** [comment]
Fair enough. I mean copying the profile data over is easy enough and it does seem maybe faster...

That said, despite having my firejail configs setup, it seems that dbus launches aren't working from thunderbird etc to open links in the existing cachy-browser instance....

**Comment by ptr1337** [comment]
> Fair enough. I mean copying the profile data over is easy enough and it does seem maybe faster...
> 
> That said, despite having my firejail configs setup, it seems that dbus launches aren't working from thunderbird etc to open links in the existing cachy-browser instance....

Well, for sure you need to adjust the firejail profile for cachy-browser.

We are currently working on a proper apparmor implementation and slowly implement also from CachyOS the application to it.

Maybe you need to set the default browser to open the correct links e.G

**Comment by ilikenwf** [comment]
For what it's worth, in the cachy-browser.local or the firejail profile, you need:

```
dbus-user filter
dbus-user.own org.cachyos.*

```
Then, for any application you want to be able to open links in an existin session:

```
dbus-user filter
dbus-user.talk org.cachyos.*
```
