### ISSUE TITLE
Latest update breaks link opening - in or out of firejail

### ISSUE THREAD

**Issue by ilikenwf** [CachyOS/CachyOS-Browser-Common#6]
After a lot of trial and error with Firejail previously I managed to get dbus/xdg link opening to work. Unfortunately, both Librewolf and Cachy-Browser now fail to open links, be it from an application, or from the console in the existing window.

I suspect that this change to dbus (notably the change to remove the openurl logic) is causing this. Librewolf also suffers the same affliction, firefox does not (both in and out of firejail):

f1020101ce5a0ed8357908cab0c6695839b580b8

Ex: have a cachy-browser window open. Run xdg-open http://google.com or cachy-browser http://google.com - you'll likely get either a new browser instance or an error that firefox is already open.

**Comment by ilikenwf** [comment]
For what it's worth they've updated that dbus patch within the last two days, so it may be time for another resync and rebuild of cachy-browser?

https://gitlab.com/librewolf-community/browser/source/-/blob/main/patches/dbus_name.patch?ref_type=heads

**Comment by ilikenwf** [comment]
I'm building with the above patch updated, with the usual dbus name cachy-browser uses. I'll report back with results.

**Comment by ilikenwf** [comment]
Grr...still getting the "close firefox" dialog.

I'm 100% this is something specific to Cachy-Browser and Librewolf though since it happens in Firefox...any ideas?

**Comment by ilikenwf** [comment]
As it turns out the most recent patches, maybe not the dbus only one, has to do with it. 

"We just fixed this, and made a new release 120.0-2, available from the deb+rpm repositories and the other usual places."

https://old.reddit.com/r/LibreWolf/comments/181q97b/cant_open_a_new_window/

**Comment by vnepogodin** [comment]
> As it turns out the most recent patches, maybe not the dbus only one, has to do with it.
> 
> "We just fixed this, and made a new release 120.0-2, available from the deb+rpm repositories and the other usual places."
> 
> https://old.reddit.com/r/LibreWolf/comments/181q97b/cant_open_a_new_window/

hmm can you try `120.0-3` version of cachy browser if its fixed there?

If not try to set env variable 'MOZ_DBUS_REMOTE=1'
